name: build-ipk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SDK_URL: https://downloads.openwrt.org/releases/24.10.2/targets/x86/64/openwrt-sdk-24.10.2-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst
      SDK_DIR: /home/runner/work/_temp/sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare zh-cn i18n Makefile (inside repo)
        shell: bash
        run: |
          set -euo pipefail
          MKDIR="package/luci-app-nodemanager/package/luci-i18n-nodemanager-zh-cn"
          mkdir -p "$MKDIR"
          {
            echo 'include $(TOPDIR)/rules.mk'
            echo ''
            echo 'PKG_NAME:=luci-i18n-nodemanager-zh-cn'
            echo 'PKG_RELEASE:=1'
            echo ''
            echo 'PKG_BUILD_DEPENDS:=luci-base/host'
            echo ''
            echo 'include $(INCLUDE_DIR)/package.mk'
            echo ''
            echo 'PO2LMO:=$(STAGING_DIR_HOSTPKG)/bin/po2lmo'
            echo ''
            echo 'define Package/$(PKG_NAME)'
            echo '  SECTION:=luci'
            echo '  CATEGORY:=LuCI'
            echo '  SUBMENU:=3. Applications'
            echo '  TITLE:=LuCI translation Chinese (zh-cn) for luci-app-nodemanager'
            echo '  PKGARCH:=all'
            echo '  DEPENDS:=+luci-app-nodemanager'
            echo 'endef'
            echo ''
            echo 'define Build/Compile'
            echo 'endef'
            echo ''
            echo 'define Package/$(PKG_NAME)/install'
            echo '@TAB@$(INSTALL_DIR) $(1)/usr/share/luci/i18n'
            echo '@TAB@set -e; \'
            echo '@TAB@PDIR=""; \'
            echo '@TAB@for d in "$(TOPDIR)/package/luci-app-nodemanager/po/zh_Hans" "$(TOPDIR)/package/luci-app-nodemanager/po/zh-cn"; do \'
            echo '@TAB@  if [ -d "$$d" ]; then PDIR="$$d"; break; fi; \'
            echo '@TAB@done; \'
            echo '@TAB@[ -n "$$PDIR" ] || { echo "ERROR: no po dir (po/zh_Hans or po/zh-cn) under luci-app-nodemanager" >&2; exit 1; }; \'
            echo '@TAB@ok=0; \'
            echo '@TAB@for p in "$$PDIR"/*.po; do \'
            echo '@TAB@  [ -f "$$p" ] || continue; \'
            echo '@TAB@  ok=1; \'
            echo '@TAB@  b=$$(basename "$$p" .po); \'
            echo '@TAB@  $(PO2LMO) "$$p" "$(1)/usr/share/luci/i18n/$$b.zh-cn.lmo"; \'
            echo '@TAB@done; \'
            echo '@TAB@[ "$$ok" -eq 1 ] || { echo "ERROR: no .po files in $$PDIR" >&2; exit 1; }'
            echo 'endef'
            echo ''
            echo '$(eval $(call BuildPackage,$(PKG_NAME)))'
          } > "$MKDIR/Makefile"
          # 把 @TAB@ 替换成真实的制表符，避免 "missing separator"
          perl -0777 -pe 's/^@TAB@/\t/mg' -i "$MKDIR/Makefile"

      - name: Download & extract OpenWrt SDK
        shell: bash
        run: |
          set -e
          mkdir -p "$SDK_DIR"
          curl -L "$SDK_URL" -o sdk.tar.zst
          tar --zstd -xf sdk.tar.zst --strip-components=1 -C "$SDK_DIR"

      - name: Prepare feeds
        shell: bash
        run: |
          set -e
          pushd "$SDK_DIR"
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          popd

      - name: Link your package into SDK
        shell: bash
        run: |
          set -e
          rm -rf "$SDK_DIR/package/luci-app-nodemanager"
          ln -s "$GITHUB_WORKSPACE" "$SDK_DIR/package/luci-app-nodemanager"

      - name: Build po2lmo (host)
        shell: bash
        run: |
          set -e
          make -C "$SDK_DIR" package/feeds/luci/luci-base/host/compile V=s

      - name: Build luci-app-nodemanager
        shell: bash
        run: |
          set -e
          make -C "$SDK_DIR" V=s -j"$(nproc)" package/luci-app-nodemanager/compile

      - name: Build zh-cn i18n
        shell: bash
        run: |
          set -e
          make -C "$SDK_DIR" V=s -j"$(nproc)" package/luci-app-nodemanager/package/luci-i18n-nodemanager-zh-cn/compile

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ipk
          path: |
            ${{ env.SDK_DIR }}/bin/targets/*/*/packages/*luci-app-nodemanager_*.ipk
            ${{ env.SDK_DIR }}/bin/targets/*/*/packages/*luci-i18n-nodemanager-zh-cn_*.ipk
