name: build-luci-app-nodemanager

on:
  workflow_dispatch:
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      PACKAGE_NAME: luci-app-nodemanager
      OWRT_VER: 24.10.2
      TARGET: x86
      SUBTARGET: 64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential git python3 cmake ninja-build zstd rsync

      - name: Download & unpack OpenWrt SDK
        shell: bash
        run: |
          set -euo pipefail
          SDK_URL="https://downloads.openwrt.org/releases/${OWRT_VER}/targets/${TARGET}/${SUBTARGET}/openwrt-sdk-${OWRT_VER}-${TARGET}-${SUBTARGET}_gcc-13.3.0_musl.Linux-x86_64.tar.zst"
          echo "SDK_URL=${SDK_URL}"
          curl -fL -o sdk.tar.zst "${SDK_URL}"
          mkdir -p "$RUNNER_TEMP/sdk"
          tar -I zstd -xf sdk.tar.zst -C "$RUNNER_TEMP/sdk"
          # 避免 pipe SIGPIPE
          tar -I zstd -tf sdk.tar.zst > /tmp/sdk.list
          SDK_BASE="$(head -1 /tmp/sdk.list | cut -d/ -f1)"
          SDK_DIR="$RUNNER_TEMP/sdk/$SDK_BASE"
          echo "SDK_DIR=$SDK_DIR" >> "$GITHUB_ENV"
          echo "SDK_BASE=$SDK_BASE" >> "$GITHUB_ENV"
          ln -s "$SDK_DIR" sdk

      - name: Sync repo into SDK/package/
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$SDK_DIR/package/${PACKAGE_NAME}"
          rsync -a --delete --exclude '.git' --exclude '.github' ./ "$SDK_DIR/package/${PACKAGE_NAME}/"

      - name: Update & install feeds
        shell: bash
        run: |
          set -euo pipefail
          cd "$SDK_DIR"
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build po2lmo/jsmin (host tools) directly
        shell: bash
        run: |
          set -euo pipefail
          cd "$SDK_DIR/feeds/luci/modules/luci-base/src"
          make -j"$(nproc)" po2lmo jsmin
          install -d "$SDK_DIR/staging_dir/hostpkg/bin"
          install -m0755 po2lmo "$SDK_DIR/staging_dir/hostpkg/bin/po2lmo"
          install -m0755 jsmin  "$SDK_DIR/staging_dir/hostpkg/bin/jsmin"

      - name: Prepare minimal .config
        shell: bash
        run: |
          set -euo pipefail
          cd "$SDK_DIR"
          rm -f .config
          {
            echo "CONFIG_TARGET_${TARGET}=y"
            echo "CONFIG_TARGET_${TARGET}_${SUBTARGET}=y"
            echo "CONFIG_PACKAGE_${PACKAGE_NAME}=m"
          } > .config
          make defconfig

      - name: Build ${{ env.PACKAGE_NAME }}
        shell: bash
        env:
          LUCI_MINIFY: "0"  # 关闭 LuCI 压缩，避免 luasrcdiet/host 依赖
        run: |
          set -euo pipefail
          cd "$SDK_DIR"
          export PATH="$PWD/staging_dir/hostpkg/bin:$PWD/staging_dir/host/bin:$PATH"
          export PO2LMO="$PWD/staging_dir/hostpkg/bin/po2lmo"
          # 串行编译，避免依赖次序导致的头文件缺失
          make -j1 V=s package/${PACKAGE_NAME}/compile

      - name: Collect .ipk artifacts
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$GITHUB_WORKSPACE/artifacts"
          find "$SDK_DIR/bin" -type f -name "*.ipk" -print -exec cp -v "{}" "$GITHUB_WORKSPACE/artifacts/" \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ipks-${{ env.OWRT_VER }}-${{ env.TARGET }}-${{ env.SUBTARGET }}
          path: artifacts/*.ipk
