name: Build luci-app-nodemanager (SDK 24.10.2)

on:
  workflow_dispatch:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SDK_URL: https://downloads.openwrt.org/releases/24.10.2/targets/x86/64/openwrt-sdk-24.10.2-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst
      SDK_DIR: /home/runner/work/_temp/sdk
      TERM: xterm-256color

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y build-essential zstd rsync gawk gettext unzip curl python3

      - name: Download & extract OpenWrt SDK
        run: |
          set -euo pipefail
          mkdir -p /home/runner/work/_temp
          cd /home/runner/work/_temp
          curl -L --retry 3 -o sdk.tar.zst "$SDK_URL"
          tar --zstd -xf sdk.tar.zst
          mv openwrt-sdk-* "$SDK_DIR"
          ls -la "$SDK_DIR"

      - name: Prepare feeds & defconfig
        run: |
          set -euo pipefail
          cd "$SDK_DIR"
          ./scripts/feeds update -a
          ./scripts/feeds install luci-base
          make defconfig

      - name: Import luci-app-nodemanager into SDK
        run: |
          set -euo pipefail
          rsync -a --delete --exclude '.git' --exclude '.github' "$GITHUB_WORKSPACE"/ "$SDK_DIR/package/luci-app-nodemanager"/
          find "$SDK_DIR/package/luci-app-nodemanager" -maxdepth 2 -type f -name Makefile -print

      - name: Build luci-app-nodemanager
        run: |
          set -euo pipefail
          make -C "$SDK_DIR" V=s -j"$(nproc)" package/luci-app-nodemanager/compile

      - name: Create zh-cn i18n Makefile (tabs preserved via Python)
        run: |
          set -euo pipefail
          python3 - <<'PY'
          import os, pathlib
          sdk = os.environ['SDK_DIR']
          d = pathlib.Path(sdk) / 'package' / 'luci-i18n-nodemanager-zh-cn'
          d.mkdir(parents=True, exist_ok=True)
          content = "\n".join([
            "include $(TOPDIR)/rules.mk",
            "",
            "LUCI_PKG_NAME:=nodemanager",
            "PKG_NAME:=luci-i18n-$(LUCI_PKG_NAME)-zh-cn",
            "PKG_RELEASE:=1",
            "",
            "include $(INCLUDE_DIR)/package.mk",
            "",
            "define Package/$(PKG_NAME)",
            "\tSECTION:=luci",
            "\tCATEGORY:=LuCI",
            "\tSUBMENU:=3. Applications",
            "\tTITLE:=Chinese (zh-cn) translation for luci-app-$(LUCI_PKG_NAME)",
            "\tDEPENDS:=+luci-app-$(LUCI_PKG_NAME)",
            "\tPKGARCH:=all",
            "endef",
            "",
            "# Build a local po2lmo with HOSTCC to avoid hostpkg dependency",
            "define Build/Compile",
            "\t$(HOSTCC) -O2 -Wall \\",
            "\t\t-o $(PKG_BUILD_DIR)/po2lmo \\",
            "\t\t$(TOPDIR)/feeds/luci/modules/luci-base/src/po2lmo.c \\",
            "\t\t$(TOPDIR)/feeds/luci/modules/luci-base/src/lmo_*.c",
            "endef",
            "",
            "define Package/$(PKG_NAME)/install",
            "\t$(INSTALL_DIR) $(1)/usr/share/luci/i18n",
            "\t@if [ -d \"$(TOPDIR)/package/luci-app-$(LUCI_PKG_NAME)/po/zh_Hans\" ]; then \\",
            "\t\tPDIR=\"$(TOPDIR)/package/luci-app-$(LUCI_PKG_NAME)/po/zh_Hans\"; \\",
            "\telif [ -d \"$(TOPDIR)/package/luci-app-$(LUCI_PKG_NAME)/po/zh-cn\" ]; then \\",
            "\t\tPDIR=\"$(TOPDIR)/package/luci-app-$(LUCI_PKG_NAME)/po/zh-cn\"; \\",
            "\telse \\",
            "\t\techo \"No po dir under luci-app-$(LUCI_PKG_NAME)\"; exit 1; \\",
            "\tfi; \\",
            "\tif [ -f \"$$PDIR/$(LUCI_PKG_NAME).po\" ]; then \\",
            "\t\tPOFILE=\"$$PDIR/$(LUCI_PKG_NAME).po\"; \\",
            "\telse \\",
            "\t\tPOFILE=\"$$(ls -1 \"$$PDIR\"/*.po 2>/dev/null | head -n1)\"; \\",
            "\tfi; \\",
            "\t[ -n \"$$POFILE\" ] || { echo \"No .po file in $$PDIR\"; exit 1; }; \\",
            "\t\"$(PKG_BUILD_DIR)/po2lmo\" \"$$POFILE\" \"$(1)/usr/share/luci/i18n/$(LUCI_PKG_NAME).zh-cn.lmo\"",
            "endef",
            "",
            "$(eval $(call BuildPackage,$(PKG_NAME)))",
            ""
          ])
          (d / 'Makefile').write_text(content)
          print("Wrote", d/'Makefile')
          PY

      - name: Build zh-cn i18n
        run: |
          set -euo pipefail
          make -C "$SDK_DIR" V=s -j"$(nproc)" package/luci-i18n-nodemanager-zh-cn/compile

      - name: Collect IPKs
        run: |
          set -euo pipefail
          mkdir -p "$GITHUB_WORKSPACE/dist"
          shopt -s nullglob
          mapfile -t FILES < <(find "$SDK_DIR/bin" -type f \( -name 'luci-app-nodemanager_*.ipk' -o -name 'luci-i18n-nodemanager-zh-cn_*.ipk' \))
          if [ "${#FILES[@]}" -eq 0 ]; then
            echo "No IPK files found under $SDK_DIR/bin"
            find "$SDK_DIR/bin" -maxdepth 3 -type d -print
            exit 1
          fi
          for f in "${FILES[@]}"; do
            cp -v "$f" "$GITHUB_WORKSPACE/dist/"
          done
          ls -al "$GITHUB_WORKSPACE/dist"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ipk-x86_64
          path: dist/
