name: Build luci-app-nodemanager (SDK 24.10.2)

on:
  workflow_dispatch:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      SDK_URL: https://downloads.openwrt.org/releases/24.10.2/targets/x86/64/openwrt-sdk-24.10.2-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst
      SDK_DIR: /home/runner/work/_temp/sdk
      TERM: xterm-256color

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential zstd libncurses5 rsync gawk gettext unzip curl

      - name: Download & extract OpenWrt SDK
        run: |
          set -euo pipefail
          mkdir -p /home/runner/work/_temp
          cd /home/runner/work/_temp
          curl -L --retry 3 -o sdk.tar.zst "$SDK_URL"
          tar --zstd -xf sdk.tar.zst
          realdir="$(ls -d openwrt-sdk-*/ | head -n1)"
          mv "$realdir" "$SDK_DIR"
          ls -la "$SDK_DIR"

      - name: Prepare feeds & defconfig
        run: |
          set -euo pipefail
          cd "$SDK_DIR"
          ./scripts/feeds update -a
          ./scripts/feeds install luci-base
          make defconfig

      - name: Import luci-app-nodemanager into SDK
        run: |
          set -euo pipefail
          rsync -a --delete --exclude '.git' --exclude '.github' "$GITHUB_WORKSPACE"/ "$SDK_DIR/package/luci-app-nodemanager"/
          find "$SDK_DIR/package/luci-app-nodemanager" -maxdepth 2 -type f -name Makefile -print

      - name: Build luci-app-nodemanager
        run: |
          set -euo pipefail
          make -C "$SDK_DIR" V=s -j"$(nproc)" package/luci-app-nodemanager/compile

      - name: Create zh-cn i18n Makefile
        run: |
          set -euo pipefail
          python3 - <<'PY'
          from textwrap import dedent
          import os, pathlib
          sdk = os.environ['SDK_DIR']
          d = pathlib.Path(sdk) / 'package' / 'luci-i18n-nodemanager-zh-cn'
          d.mkdir(parents=True, exist_ok=True)
          content = dedent('''\
          include $(TOPDIR)/rules.mk

          LUCI_PKG_NAME:=nodemanager
          PKG_NAME:=luci-i18n-$(LUCI_PKG_NAME)-zh-cn
          PKG_RELEASE:=1

          include $(INCLUDE_DIR)/package.mk

          define Package/$(PKG_NAME)
            SECTION:=luci
            CATEGORY:=LuCI
            SUBMENU:=3. Applications
            TITLE:=Chinese (zh-cn) translation for luci-app-$(LUCI_PKG_NAME)
            DEPENDS:=+luci-app-$(LUCI_PKG_NAME)
            PKGARCH:=all
          endef

          define Build/Compile
          	true
          endef

          define Package/$(PKG_NAME)/install
          	$(INSTALL_DIR) $(1)/usr/share/luci/i18n
          	if [ -d "$(TOPDIR)/package/luci-app-$(LUCI_PKG_NAME)/po/zh_Hans" ]; then \
          	  PDIR="$(TOPDIR)/package/luci-app-$(LUCI_PKG_NAME)/po/zh_Hans"; \
          	elif [ -d "$(TOPDIR)/package/luci-app-$(LUCI_PKG_NAME)/po/zh-cn" ]; then \
          	  PDIR="$(TOPDIR)/package/luci-app-$(LUCI_PKG_NAME)/po/zh-cn"; \
          	else \
          	  echo "No po dir under luci-app-$(LUCI_PKG_NAME)"; exit 1; \
          	fi; \
          	# Prefer nodemanager.po; otherwise pick the first .po
          	if [ -f "$$PDIR/$(LUCI_PKG_NAME).po" ]; then \
          	  POFILE="$$PDIR/$(LUCI_PKG_NAME).po"; \
          	else \
          	  POFILE=$$(ls -1 "$$PDIR"/*.po 2>/dev/null | head -n1); \
          	fi; \
          	[ -n "$$POFILE" ] || { echo "No .po file in $$PDIR"; exit 1; }; \
          	PO2LMO="$(STAGING_DIR_HOSTPKG)/bin/po2lmo"; \
          	if [ ! -x "$$PO2LMO" ]; then \
          	  $$(MAKE) -C "$(TOPDIR)/feeds/luci/modules/luci-base/src" po2lmo; \
          	  PO2LMO="$(TOPDIR)/feeds/luci/modules/luci-base/src/po2lmo"; \
          	fi; \
          	[ -x "$$PO2LMO" ] || { echo "po2lmo not available"; exit 1; }; \
          	"$$PO2LMO" "$$POFILE" "$(1)/usr/share/luci/i18n/$(LUCI_PKG_NAME).zh-cn.lmo"
          endef

          $(eval $(call BuildPackage,$(PKG_NAME)))
          ''')
          (d/'Makefile').write_text(content)
          print("Wrote", d/'Makefile')
          PY

      - name: Build zh-cn i18n
        run: |
          set -euo pipefail
          make -C "$SDK_DIR/feeds/luci/modules/luci-base/src" po2lmo
          make -C "$SDK_DIR" V=s -j"$(nproc)" package/luci-i18n-nodemanager-zh-cn/compile

      - name: Collect IPKs
        run: |
          set -euo pipefail
          mkdir -p "$GITHUB_WORKSPACE/dist"
          shopt -s nullglob
          mapfile -t FILES < <(find "$SDK_DIR/bin" -type f \( -name 'luci-app-nodemanager_*.ipk' -o -name 'luci-i18n-nodemanager-zh-cn_*.ipk' \))
          if [ "${#FILES[@]}" -eq 0 ]; then
            echo "No IPK files found under $SDK_DIR/bin"
            find "$SDK_DIR/bin" -maxdepth 3 -type d -print
            exit 1
          fi
          for f in "${FILES[@]}"; do
            cp -v "$f" "$GITHUB_WORKSPACE/dist/"
          done
          ls -al "$GITHUB_WORKSPACE/dist"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ipk-x86_64
          path: dist/
